---
- name: Install Zsh
  apt:
    name: zsh
    state: present
  become: yes

- name: Set Zsh as default shell
  user:
    name: "{{ user_name }}"
    shell: /usr/bin/zsh
  become: yes

- name: Check if Oh My Zsh is installed
  stat:
    path: "{{ user_home }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: not oh_my_zsh_stat.stat.exists
  args:
    creates: "{{ user_home }}/.oh-my-zsh"

- name: Install Spaceship Prompt
  git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: "{{ user_home }}/.oh-my-zsh/custom/themes/spaceship-prompt"
    depth: 1

- name: Create symlink for Spaceship theme
  file:
    src: "{{ user_home }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{ user_home }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link

- name: Configure .zshrc
  template:
    src: zshrc.j2
    dest: "{{ user_home }}/.zshrc"
    mode: '0644'
