---
- name: Download Discord .deb
  get_url:
    url: "https://discord.com/api/download?platform=linux&format=deb"
    dest: "/tmp/discord.deb"
    mode: '0644'
  ignore_errors: yes

- name: Install Discord
  apt:
    deb: "/tmp/discord.deb"
    state: present
  become: yes
  ignore_errors: yes
