---
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: Install Docker and Podman
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - podman
    state: present
  become: yes

- name: Add user to docker group
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes
  become: yes

- name: Install lazydocker
  shell: |
    curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  args:
    creates: "{{ user_home }}/.local/bin/lazydocker"
