---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install system essentials
  apt:
    name:
      - curl
      - wget
      - jq
      - git
      - git-lfs
      - build-essential
      - unzip
      - software-properties-common
      - tree
      - htop
      - rsync
      - make
      - cmake
      - autoconf
      - parallel
      - procps
      - gpg
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - pipx
      - python3-venv
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
    state: present
  become: yes

- name: Install media tools
  apt:
    name:
      - ffmpeg
      - imagemagick
      - tesseract-ocr
    state: present
  become: yes

- name: Install system utilities
  apt:
    name:
      - tmux
      - vim
      - neovim
    state: present
  become: yes

- name: Download HyperJS
  get_url:
    url: https://releases.hyper.is/download/deb
    dest: /tmp/hyper.deb
    mode: '0644'

- name: Install HyperJS
  apt:
    deb: /tmp/hyper.deb
  become: yes

- name: Install Hyper plugins
  shell: hyper i {{ item }}
  loop:
    - hypercwd
    - hyper-pane
    - hyperpower
  args:
    creates: "{{ user_home }}/.hyper_plugins/node_modules/{{ item }}"
